# Generated by Django 2.0 on 2021-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211021_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='ad_created',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
